#!/usr/bin/ksh
#	20070714 CheeYoung O	Replaced echo with printf
#	20051129 CheeYoung O	MySQL Connector/J 3.1.11
#	20050103 CheeYoung O	Solaris/7/x86
#	20041027 CheeYoung O	Solaris/8/SPARC, Added -showversion 
#	20040702 CheeYoung O	Check existence of .class file
#	20040629 CheeYoung O	Added JAVA_HOME
#	20040521 CheeYoung O	HP-UX/11.11
#       20040411 CheeYoung O	Linux/RedHat/9
#       20040409 CheeYoung O	Linux/RedHat/AS/2.1
#       20031104 CheeYoung O

CLASS_NAME="GenerateDocuments"

#ORACLE_BASE=/app/oracle
#ORACLE_HOME=$ORACLE_BASE/ias/9.0.4
#export ORACLE_BASE ORACLE_HOME 

#	MySQL Connector/J 5.0.3
#CLASSPATH=.:$HOME/share/jdbc/mysql/5.0.3/mysql-connector-java-5.0.3-bin.jar

#	Oracle JDBC Driver
#	JDK 1.3.1_x and JDK 1.2.2_x
#CLASSPATH=.:$ORACLE_HOME/jdbc/lib/classes12_g.zip
#	JDK 1.4.2_x and 1.4.1_x
#CLASSPATH=.:$HOME/share/jdbc/oracle/92060/ojdbc14_g.jar
CLASSPATH=.:$HOME/share/jdbc/oracle/A2030/ojdbc14_g.jar
export CLASSPATH 

#	Oracle JDBC OCI Driver
#LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
#LD_LIBRARY_PATH=$ORACLE_HOME/lib32:$LD_LIBRARY_PATH
#LD_LIBRARY_PATH_64=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
#SHLIB_PATH=$LD_LIBRARY_PATH
#LIBPATH=$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH
#export LD_LIBRARY_PATH_64 SHLIB_PATH LIBPATH

TEXT_EDITOR="/usr/bin/vi"
#JAVA_HOME=$ORACLE_HOME/jdk
JAVA_HOME=/app/jdk/1.4.2_06
#JAVA_HOME=/app/jdk/1.3.1_09

# Java Compiler and its Options
JAVAC=$JAVA_HOME/bin/javac
JAVAC_OPTS="-g -verbose"
#JAVAC_OPTS="-deprecation -g"

# JVM and its Options
JVM=$JAVA_HOME/bin/java
JVM_OPTS="-showversion"
JVM_150_OPTS=""
JVM_142_OPTS="-Xrunhprof:file=prof_$CLASS_NAME.txt -Xmx16m -Xloggc:gc_$CLASS_NAME.log"
JVM_131_OPTS="-Xrunhprof -Xmx16m -verbose:gc"
#JVM_OPTS=$JVM_142_OPTS
#JVM_OPTS="$JVM_OPTS $JVM_131_OPT"

# Return Codes
ERR_NO_TEXT_EDITOR_FILE=11
ERR_NO_JAVAC_FILE=21
ERR_NO_JVM_FILE=22
ERR_NO_SOURCE_FILE=31
ERR_NO_BYTECODE_FILE=41

if [ ! -f $JAVAC ]; then
	echo "$JAVAC does not exist."
	exit $ERR_NO_JAVAC_FILE;
fi
if [ ! -f $JVM ]; then
	echo "$JVM does not exist."
	exit $ERR_NO_JVM_FILE;
fi

if [ ! -f $TEXT_EDITOR ]; then
        echo "$TEXT_EDITOR does not exist."
        exit $ERR_NO_TEXT_EDITOR_FILE;
fi
$TEXT_EDITOR $CLASS_NAME.java
RET_CODE=$?
if [ "$RET_CODE" != "0" ]; then
        printf "\a%s: Editor = $TEXT_EDITOR returned %s\n" $LINENO $TEXT_EDITOR $RET_CODE
        exit $RET_CODE
fi

if [ ! -f "$CLASS_NAME.java" ]; then
        printf "\a%s: %s.java does not exist.\n" $LINENO $CLASS_NAME
        exit $ERR_NO_SOURCE_FILE;
fi
clear
$JAVAC $JAVAC_OPTS $CLASS_NAME.java
RET_CODE=$?
if [ "$RET_CODE" != "0" ]; then
        printf "\a%s: Java Compiler returned %s\n" $LINENO $RET_CODE
        exit $RET_CODE
fi

#	Compilation Only
exit $RET_CODE

if [ ! -f "$CLASS_NAME.class" ]; then
	printf "\a%s: %s.class does not exist.\n" $LINENO $CLASS_NAME
	exit $ERR_NO_BYTECODE_FILE;
fi

$JVM $JVM_OPTS $CLASS_NAME
RET_CODE=$?
if [ "$RET_CODE" != "0" ]; then
	printf "\a%s: Java VM returned %s\n" $LINENO $RET_CODE
	exit $RET_CODE
fi
